/**
 * Feeds Gemini's views (#381) from the shared map (ADR 2026-10-03,
 * Decision 3). Gemini's prototype carried hand-written syntheses, facets and
 * cause trees per node; here they are derived from the statements, their
 * `label`/`link` phrases and the relation kinds, so the views work for any
 * repository's map. Pure, no DOM.
 */

import type {
  EdgeKind,
  MapIndex,
  Neighbor,
} from "../../../src/cli/knowledge-map/model.js";
import { conceptLabel, conceptProposition } from "./concept-layout.js";
import { rankNeighbors, relationLabelKey } from "./layout.js";

/** One related statement, with the sentence that joins it to the focus. */
export interface RelatedItem {
  id: string;
  /** "ZAM rests on Beliefs" when both labels and a phrase exist. */
  proposition: string | null;
  /** i18n key of the sentence connective, as a fallback reading. */
  connectiveKey: string;
  kind: EdgeKind;
  text: string;
}

export type AnchorType =
  | "adr"
  | "okf"
  | "test"
  | "schema"
  | "config"
  | "docs"
  | "code";

export interface Anchor {
  path: string;
  type: AnchorType;
  /** Where the path opens, when the map names its repository URL. */
  url: string | null;
}

export function anchorType(path: string): AnchorType {
  const lower = path.toLowerCase();
  if (lower.includes("docs/adr/") || /(^|\/)adr[-_/]/.test(lower)) return "adr";
  if (lower.includes("docs/okf/")) return "okf";
  if (
    /(^|\/)(tests?|__tests__|spec)\//.test(lower) ||
    /\.(test|spec)\./.test(lower)
  ) {
    return "test";
  }
  if (lower.includes("schema")) return "schema";
  if (/\.(json|ya?ml|toml|ini|env)$/.test(lower) || lower.includes("config")) {
    return "config";
  }
  if (/\.(md|mdx|txt|rst|adoc)$/.test(lower)) return "docs";
  return "code";
}

export function relatedItem(
  index: MapIndex,
  focusId: string,
  neighbor: Neighbor,
): RelatedItem {
  const proposition = conceptProposition(index, focusId, neighbor);
  const from = proposition ? index.get(proposition.fromId) : undefined;
  const to = proposition ? index.get(proposition.toId) : undefined;
  return {
    id: neighbor.id,
    proposition:
      proposition && from && to
        ? `${conceptLabel(from)} ${proposition.phrase} ${conceptLabel(to)}`
        : null,
    connectiveKey: relationLabelKey(neighbor),
    kind: neighbor.kind,
    text: index.get(neighbor.id)?.text ?? neighbor.id,
  };
}

/** Every neighbour, most relevant first, as items. */
export function relatedItems(
  index: MapIndex,
  focusId: string,
  previous: string | null = null,
): RelatedItem[] {
  return rankNeighbors(index, focusId, previous).map((neighbor) =>
    relatedItem(index, focusId, neighbor),
  );
}

/**
 * The macro-statement (Kintsch): the concept sentences around the focus read
 * as one paragraph. Derived from the map, never generated by a model.
 */
export function macroSynthesis(index: MapIndex, focusId: string): string {
  return relatedItems(index, focusId)
    .map((item) => item.proposition)
    .filter((sentence): sentence is string => sentence !== null)
    .map((sentence) => (/[.!?…]$/.test(sentence) ? sentence : `${sentence}.`))
    .join(" ");
}

export function anchorsOf(index: MapIndex, focusId: string): Anchor[] {
  return (index.get(focusId)?.sources ?? []).map((path) => ({
    path,
    type: anchorType(path),
    url: index.sourceUrl(path),
  }));
}

/**
 * Gemini's cause tree: what the focus rests on to the left, what follows
 * from it to the right. Reasons, preconditions, the parent, causes and the
 * general case lead in; details, consequences, dependants, examples and
 * rejected alternatives lead out.
 */
export function causeTree(
  index: MapIndex,
  focusId: string,
): { upstream: RelatedItem[]; downstream: RelatedItem[] } {
  const upstream: RelatedItem[] = [];
  const downstream: RelatedItem[] = [];
  for (const neighbor of rankNeighbors(index, focusId, null)) {
    const item = relatedItem(index, focusId, neighbor);
    const out = neighbor.direction === "out";
    const leadsIn =
      neighbor.tree === "parent" ||
      (out && (neighbor.kind === "because" || neighbor.kind === "requires")) ||
      (out && neighbor.kind === "uses") ||
      (!out && (neighbor.kind === "leads_to" || neighbor.kind === "example"));
    (leadsIn ? upstream : downstream).push(item);
  }
  return { upstream, downstream };
}

export interface Facets {
  /** Why it exists: what it belongs to, then its reasons. */
  purpose: RelatedItem[];
  /** What it connects to at run time, leads to, or breaks down into. */
  connections: RelatedItem[];
  /** What must hold, and what was decided against. */
  rules: RelatedItem[];
  /** Where to look in the repository. */
  places: Anchor[];
}

/** Every neighbour lands in exactly one zone, so each stays reachable. */
export function facetsOf(index: MapIndex, focusId: string): Facets {
  const purpose: RelatedItem[] = [];
  const connections: RelatedItem[] = [];
  const rules: RelatedItem[] = [];
  let parent: RelatedItem | null = null;
  for (const neighbor of rankNeighbors(index, focusId, null)) {
    const item = relatedItem(index, focusId, neighbor);
    const out = neighbor.direction === "out";
    if (out && neighbor.kind === "because") {
      purpose.push(item);
    } else if (neighbor.kind === "requires" || neighbor.kind === "instead_of") {
      rules.push(item);
    } else if (neighbor.tree === "parent") {
      parent = item;
    } else {
      connections.push(item);
    }
  }
  if (parent) purpose.unshift(parent);
  return { purpose, connections, rules, places: anchorsOf(index, focusId) };
}
