// swift-tools-version:5.9
// 5.9 is the floor for `.iOS(.v17)`; the official plugin packages declare 5.3
// only because they target .v13. Keep this in step with the deployment target
// in tauri.conf.json and gen/apple/project.yml.
import PackageDescription

// The iOS plugins must live in a SwiftPM package that the *Rust* build links,
// not in the Xcode app target. The Rust staticlib links before Swift is
// compiled, so `@_cdecl` symbols sitting in the app target are invisible to it
// and the build fails with "Undefined symbols: _init_plugin_secure_pairing".
//
// This mirrors the layout every official plugin uses (see
// tauri-plugin-barcode-scanner's ios/). `../.tauri/tauri-api` is generated by
// build.rs from DEP_TAURI_IOS_LIBRARY_PATH and is not versioned.
let package = Package(
  name: "zam-mobile",
  platforms: [.iOS(.v17)],
  products: [
    .library(name: "zam-mobile", type: .static, targets: ["zam-mobile"])
  ],
  dependencies: [
    // The staged package declares itself as "Tauri"; `.package(path:)` infers
    // that, avoiding the `.package(name:path:)` form deprecated since 5.6.
    .package(path: "../.tauri/tauri-api")
  ],
  targets: [
    .target(
      name: "zam-mobile",
      // `.package(path:)` takes its identity from the directory name
      // (tauri-api), not from the "Tauri" declared inside it, so the product
      // has to be addressed explicitly rather than by name.
      dependencies: [.product(name: "Tauri", package: "tauri-api")],
      path: "Sources")
  ]
)
