// swift-tools-version:5.3
import PackageDescription

// The iOS plugins must live in a SwiftPM package that the *Rust* build links,
// not in the Xcode app target. The Rust staticlib links before Swift is
// compiled, so `@_cdecl` symbols sitting in the app target are invisible to it
// and the build fails with "Undefined symbols: _init_plugin_secure_pairing".
//
// This mirrors the layout every official plugin uses (see
// tauri-plugin-barcode-scanner's ios/). `../.tauri/tauri-api` is generated by
// build.rs from DEP_TAURI_IOS_LIBRARY_PATH and is not versioned.
let package = Package(
  name: "zam-mobile",
  platforms: [.iOS(.v17)],
  products: [
    .library(name: "zam-mobile", type: .static, targets: ["zam-mobile"])
  ],
  dependencies: [
    .package(name: "Tauri", path: "../.tauri/tauri-api")
  ],
  targets: [
    .target(
      name: "zam-mobile",
      dependencies: [.byName(name: "Tauri")],
      path: "Sources")
  ]
)
